vagrant_version: "2"
k3s_version: "v1.21.9+k3s1"
kubeconfig_mode: "644"
image: "bumoad/spinbox"
image_version": "0.3.0"
ip: "192.168.3.31"
db:
  user: "minioadmin"
  password: "minioadmin"
  port: "9010"
node:
  name: "spinbox"
  count: 1
  gui: true
  resources:
    memory: "8196"
    cpu: "4"
